apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: rpchan44/laravel-apache-php81
        resources:
          requests:
            cpu: "400m"
        ports:
        - containerPort: 80

