apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app  # This matches the label of the Deployment Pods
  ports:
    - protocol: TCP
      port: 80          # The port on which the service will be accessible
      targetPort: 80     # The port inside the Pod that the service will forward traffic to
  type: ClusterIP        # Exposes the service inside the cluster (default)

