name: Publish Docker image and update k8s manifest

on:
  pull_request:
    paths:
      - '**/*.php'  # Run on any Python file change
  push:
    branches: 
      - main
      - development

jobs:
   push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo with Dockerfile
        uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rpchan44/laravel-app

      - name: Build Docker image
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker build --build-arg MYENV=${{ secrets.ENV }} ENVIRONMENT=production -t rpchan44/laravel-apache-php81-prod:${{ github.sha }} .
          else
            docker build --build-arg MYENV=${{ secrets.ENV }} ENVIRONMENT=development -t rpchan44/laravel-apache-php81-dev:${{ github.sha }} .
          fi
      
      - name: Push Docker image to DockerHub
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker push rpchan44/laravel-apache-php81-prod:${{ github.sha }}
          else
            docker push rpchan44/laravel-apache-php81-dev:${{ github.sha }}
          fi
